seed: 42
do_train: True
do_predict: True 
do_ED_infer: True 

# top-level config #
paradigm: sequence_labeling
task_name: ED
dataset_name: DuEE1.0
language: Chinese
test_exists_labels: False

# file path #
output_dir: output/DuEE1.0
type2id_path: ../../data/processed/DuEE1.0/label2id.json
train_file: ../../data/processed/DuEE1.0/train.unified.jsonl
validation_file: ../../data/processed/DuEE1.0/valid.unified.jsonl
test_file: ../../data/processed/DuEE1.0/test.unified.jsonl

# config for data processor #
return_token_type_ids: True
truncate_in_batch: False
truncate_seq2seq_output: False

# model config #
model_type: bert
model_name_or_path: bert-base-chinese
hidden_size: 768
aggregation: none

# training config #
num_train_epochs: 20
max_seq_length: 200
max_out_length: 200
dataloader_num_workers: 1

per_device_train_batch_size: 2
per_device_eval_batch_size: 1
gradient_accumulation_steps: 1
# eval_accumulation_steps: 4
learning_rate: 5.0e-5
weight_decay: 1.0e-5
warmup_ratio: 0.1 
max_grad_norm: 1
optim: adamw_torch

load_best_model_at_end: True
metric_for_best_model: micro_f1 
greater_is_better: True 

logging_strategy: steps
logging_steps: 100
evaluation_strategy: epoch
eval_steps: 500
save_strategy: epoch
save_steps: 500
save_total_limit: 1

# split inference #
split_infer: True
split_infer_size: 1000


